from typing import Protocol, runtime_checkable

@runtime_checkable
class ReceiptImageStorage(Protocol):
    def put(self, key: str, data: bytes, content_type: str) -> None: ...
    def get(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...
