"""Tao persistence hoa don V2 additive
Revision ID: 20260921_v2
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "20260921_v2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_v2_receipts",
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=80), nullable=False),
        sa.Column("source_group", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("processing_stage", sa.String(length=32), nullable=True),
        sa.Column("processing_error", sa.JSON(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("active_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("latest_ocr_run_id", sa.String(length=36), nullable=True),
        sa.Column("latest_kie_run_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("verified_at", sa.String(length=40), nullable=True),
        sa.CheckConstraint(
            "status IN ('UPLOADED','PROCESSING','NEEDS_REVIEW','VERIFIED','FAILED')",
            name="invoice_v2_status",
        ),
        sa.PrimaryKeyConstraint("receipt_id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_invoice_v2_receipts_created_at"),
        "invoice_v2_receipts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_v2_receipts_status"),
        "invoice_v2_receipts",
        ["status"],
        unique=False,
    )
    op.create_table(
        "invoice_v2_attempts",
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("active_receipt_id", sa.String(length=36), nullable=True),
        sa.Column("ocr_run_id", sa.String(length=36), nullable=False),
        sa.Column("kie_run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("lease_until", sa.Float(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["invoice_v2_receipts.receipt_id"],
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
        sa.UniqueConstraint("active_receipt_id"),
        sa.UniqueConstraint("kie_run_id"),
        sa.UniqueConstraint("ocr_run_id"),
    )
    op.create_index(
        op.f("ix_invoice_v2_attempts_lease_until"),
        "invoice_v2_attempts",
        ["lease_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_v2_attempts_receipt_id"),
        "invoice_v2_attempts",
        ["receipt_id"],
        unique=False,
    )
    op.create_table(
        "invoice_v2_audit",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("section", sa.String(length=8), nullable=True),
        sa.Column("row_id", sa.String(length=128), nullable=True),
        sa.Column("field", sa.String(length=64), nullable=True),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["invoice_v2_receipts.receipt_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_invoice_v2_audit_receipt_id"),
        "invoice_v2_audit",
        ["receipt_id"],
        unique=False,
    )
    op.create_table(
        "invoice_v2_outbox",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("sent_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["invoice_v2_receipts.receipt_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_invoice_v2_outbox_receipt_id"),
        "invoice_v2_outbox",
        ["receipt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_v2_outbox_sent"), "invoice_v2_outbox", ["sent"], unique=False
    )
    op.create_table(
        "invoice_v2_machine_runs",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("source_ocr_run_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["invoice_v2_attempts.attempt_id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["invoice_v2_receipts.receipt_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_ocr_run_id"],
            ["invoice_v2_machine_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("attempt_id", "kind", name="uq_invoice_v2_attempt_kind"),
    )
    op.create_index(
        op.f("ix_invoice_v2_machine_runs_receipt_id"),
        "invoice_v2_machine_runs",
        ["receipt_id"],
        unique=False,
    )
    op.create_table(
        "invoice_v2_cells",
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("section", sa.String(length=8), nullable=False),
        sa.Column("row_id", sa.String(length=128), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("kie_run_id", sa.String(length=36), nullable=False),
        sa.Column("machine", sa.JSON(), nullable=False),
        sa.Column("correction", sa.JSON(), nullable=True),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kie_run_id"],
            ["invoice_v2_machine_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["invoice_v2_receipts.receipt_id"],
        ),
        sa.PrimaryKeyConstraint("receipt_id", "section", "row_id", "field"),
    )
    op.create_index(
        op.f("ix_invoice_v2_cells_kie_run_id"),
        "invoice_v2_cells",
        ["kie_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        for action in ("UPDATE", "DELETE"):
            op.execute(
                f"CREATE TRIGGER invoice_v2_runs_no_{action.lower()} BEFORE {action} ON invoice_v2_machine_runs BEGIN SELECT RAISE(ABORT, 'Machine runs are immutable'); END"
            )
    elif dialect == "postgresql":
        op.execute(
            "CREATE FUNCTION invoice_v2_immutable_run() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Machine runs are immutable'; END; $$"
        )
        op.execute(
            "CREATE TRIGGER invoice_v2_runs_immutable BEFORE UPDATE OR DELETE ON invoice_v2_machine_runs FOR EACH ROW EXECUTE FUNCTION invoice_v2_immutable_run()"
        )


def downgrade():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER invoice_v2_runs_immutable ON invoice_v2_machine_runs")
        op.execute("DROP FUNCTION invoice_v2_immutable_run()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_v2_cells_kie_run_id"), table_name="invoice_v2_cells")
    op.drop_table("invoice_v2_cells")
    op.drop_index(
        op.f("ix_invoice_v2_machine_runs_receipt_id"),
        table_name="invoice_v2_machine_runs",
    )
    op.drop_table("invoice_v2_machine_runs")
    op.drop_index(op.f("ix_invoice_v2_outbox_sent"), table_name="invoice_v2_outbox")
    op.drop_index(
        op.f("ix_invoice_v2_outbox_receipt_id"), table_name="invoice_v2_outbox"
    )
    op.drop_table("invoice_v2_outbox")
    op.drop_index(op.f("ix_invoice_v2_audit_receipt_id"), table_name="invoice_v2_audit")
    op.drop_table("invoice_v2_audit")
    op.drop_index(
        op.f("ix_invoice_v2_attempts_receipt_id"), table_name="invoice_v2_attempts"
    )
    op.drop_index(
        op.f("ix_invoice_v2_attempts_lease_until"), table_name="invoice_v2_attempts"
    )
    op.drop_table("invoice_v2_attempts")
    op.drop_index(
        op.f("ix_invoice_v2_receipts_status"), table_name="invoice_v2_receipts"
    )
    op.drop_index(
        op.f("ix_invoice_v2_receipts_created_at"), table_name="invoice_v2_receipts"
    )
    op.drop_table("invoice_v2_receipts")
    # ### end Alembic commands ###
